### ISSUE TITLE
search not working correctly

### ISSUE THREAD

**Issue by BluesDriveMonster** [LeagueDevelopers/lol-skins-viewer#15]
While looking up a skin line in my LoLSkinViewer I noticed something is off with the search feature. I use the French localisation of the game, which shows up fine in the client and LSV. 

When searching for Dark Star skins ("du pulsar sombre" in french, which is what I'm typing in the searchbox) something wrong happens. I own both Dark Star Orianna and Dark Star Thresh, but only DS Thresh appears when searching "pulsar", neither appear when searching "sombre", and both appear when searching "du".

In the same vein, Super Galaxy skins are called "Super (champion) intergalactique" in French. Searching for "super" brings them up but not searching "intergalactique".

And my third test, on Championship skins ("championnat") brings up Zed and Riven, but not Shyvana.

I have not yet tested in other languages or on unowned skins, but there definitively is something wrong from the research as it omits skins corresponding to the search for no clear reason.

**Comment by s-coimbra21** [comment]
I've only tested using the default English client. If you search using the English names, do the skins show up?

**Comment by BluesDriveMonster** [comment]
Everything works normally in the English client.

**Comment by s-coimbra21** [comment]
Yes but what if you use the french client and search for a skin using its English name?

**Comment by BluesDriveMonster** [comment]
Nothing appears if I try using the English name in the French client. Other skins appear correctly when typing in their french name, I have only noticed those three "lines" for now.
