### ISSUE TITLE
Export Skins

### ISSUE THREAD

**Issue by strexicious** [LeagueDevelopers/lol-skins-viewer#17]
Hello, I'm a developer from [LoLPoro](https://lolporo.com) and I'd like to talk to collaborate with the author of this app. Currently I've downloaded a clone of this app and integrated a feature to upload skins to our website, but I'd like to make that an official feature added by you guys and in return we would credit you on our website. Or maybe we can agree to some other terms.

**Comment by s-coimbra21** [comment]
Since this feature has been requested to me via private messages, I'll consider it under one condition:

The feature must be universal, not targeted at a specific site/service, like exporting a base64 JSON which anyone can integrate with.

If you are still interested in providing that functionality on your site, I will gladly add that export function.

**Comment by strexicious** [comment]
Ye, I am totally cool with that. Since its open-source it would make sense that anyone could integrate it. So please add the export function. Thanks for the response.

**Comment by s-coimbra21** [comment]
I will work on this tomorrow then.

**Comment by strexicious** [comment]
Ok. Let me know if I can help out with it.

**Comment by s-coimbra21** [comment]
Just pushed an update to branch `share`. Users will paste a link here and upload a JSON with the following format:

```javascript
{
  summonerId: number,
  skins: [{
      skinId: number
      rpValue: number
  }]
}
```

You are recommended to provide an interface that generates a one-time temporary link for you users.

If you decide to go forward and integrate this on your site I'll publish a new version of this application with the export feature available.

**Comment by strexicious** [comment]
Ok, I talked to my team members and they agreed to it. We really like the export functionality. However currently I am the only one with the app dev. env. setup so my team members will aprreciate if you release a new version of it. Thanks again. Really happy to work with you.

**Comment by s-coimbra21** [comment]
You're free to package the app and give them a zipped folder. You can use `npm run package-win` for that.

**Comment by strexicious** [comment]
is there a way to talk to u privately? any social media id or discord even?

**Comment by s-coimbra21** [comment]
You can my email `me@jinx.pro`

**Comment by strexicious** [comment]
Can you please checkout your inbox? My friend sent you an email. I will close this issue when you respond.

**Comment by s-coimbra21** [comment]
The request sends `platformId` now
