### ISSUE TITLE
"NO Connection"

### ISSUE THREAD

**Issue by Reynbow** [LeagueDevelopers/lol-skins-viewer#21]
It just sits here indefinitely. What's going on?

How do I make it work?

https://i.imgur.com/FN2sHbJ.png

**Comment by jfisher446** [comment]
Do you open your LOL client before opening this app? You should be.

**Comment by Reynbow** [comment]
I did @jfisher446 

I opened my League Launcher, logged in. Then opened this app.

**Comment by MachDog** [comment]
I have the same problem
