### ISSUE TITLE
How to find link to crawl data skin/champion

### ISSUE THREAD

**Issue by pthiep** [LeagueDevelopers/lol-skins-viewer#22]
Hi ! I use your' source code to code an application by C# to check skin and champ
And i want check more info, i used Fiddler to find link  crawl data
Example you :
 /lol-champions/v1/inventories/${summoner.id}/champions` 
/lol-collections/v1/inventories/${summoner.id}/champion-mastery`
So you can help me how to find it to crawl another info 
Thank you every much ^_^

**Comment by Acen** [comment]
Do you mean the API?
https://developer.riotgames.com/api-methods/

**Comment by pthiep** [comment]
Thank for support :D 
But i can't use api it to crawl in garena 
You can see code by lol-skin-view crawl http://127.0.0.1:id+pass/link 
It different with api riot ^^l

**Comment by Acen** [comment]
Ah damn! Sorry to hear that!
Could their application be decompiled to pull from? (Android App)
