### ISSUE TITLE
Add the option to make each skin picture smaller, so more skins fit on the same page.

### ISSUE THREAD

**Issue by AmauryLepicard** [LeagueDevelopers/lol-skins-viewer#23]
Hey there.
I' have quite a lot of skin, and right now I can see at most 12 of them.
Could you add an option to resize them?

I've cloned your repo, but I've never developed with JS, and I don't even know how to compile your code :)

Thanks!

EDIT: And how the hell can I add the label Feature to my request?

**Comment by s-coimbra21** [comment]
Hi, Riot is launching a skins feature in the official client soon, so I don't have any intention to continue developing this project at the moment.
